name: Deploy sur la VM

on:
  workflow_run:
    workflows: ["Build & Push image"]
    types: [completed]
  workflow_dispatch:

env:
  IMAGE: ${{ vars.ARTIFACT_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO_ID }}/quelpoke

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Deploy
        run: |
          gcloud compute ssh ${{ secrets.GCP_VM_NAME }} \
            --zone ${{ secrets.GCP_VM_ZONE }} \
            --project ${{ vars.GCP_PROJECT_ID }} \
            --quiet \
            --command "
              gcloud auth configure-docker ${{ vars.ARTIFACT_LOCATION }}-docker.pkg.dev --quiet
              docker pull $IMAGE:latest
              docker rm -f quelpoke || true
              docker run -d --name quelpoke -p 80:8080 --restart unless-stopped $IMAGE:latest
            "
